"""empty message

Revision ID: bfbac6c91c51
Revises: 
Create Date: 2024-12-20 16:36:50.891939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfbac6c91c51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('_nama', sa.String(length=100), nullable=False),
    sa.Column('_alamat', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('_nama')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
